### ISSUE TITLE
HA 0.90.1 broke the besmart custom component

### ISSUE THREAD

**Issue by faxbio** [muchasuerte/home-assistant#2]
Hi, it's me again.
Upgrading HA to later than 0.89 the custom component doesn't work anymore.
I suppose something changed in the climate base component.
The log reports:

og Details (ERROR)
Wed Mar 27 2019 02:23:40 GMT+0100 (Ora standard dell’Europa centrale)
Error loading custom_components.climate.besmart. Make sure all dependencies are installed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/homeassistant/loader.py", line 166, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.7/importlib/_init_.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/config/custom_components/climate/besmart.py", line 21, in <module>
    from homeassistant.components.climate import (ClimateDevice,
ImportError: cannot import name 'SUPPORT_TARGET_TEMPERATURE' from 'homeassistant.components.climate' (/usr/local/lib/python3.7/site-packages/homeassistant/components/climate/_init_.py)

any plan to fix it? let me know if i can help somehow

**Comment by muchasuerte** [comment]
hi @faxbio  yes I know I have to change also the folder name from climate to besmart there are new guide lines to follow for custom component, unfortunately I have not so much time right now to fix all, so thank you very much for your contribution

**Comment by renzorlive** [comment]
I also have a besmart thermostat but I could not get the username and password for the wifibox, it's a default one?

**Comment by faxbio** [comment]
Hi, you need to install the android app, connect to the thermostat and configure the centralized “cloud” account. That credencials are the one to be used.

The other “standard” code password are 63 to access the tecnician page and 18 (if I remember correctly) to access the TSP feature.
But those are usable in the app and almost reserved to a tecnician.

Fabio


Da: RNZ
Inviato: venerdì 26 aprile 2019 12:08
A: muchasuerte/home-assistant
Cc: faxbio; Mention
Oggetto: Re: [muchasuerte/home-assistant] HA 0.90.1 broke the besmart customcomponent (#2)

I also have a besmart thermostat but I could not get the username and password for the wifibox, it's a default one?

**Comment by muchasuerte** [comment]
Hello all, 

today my children let me play a bit with HASS so I was able to fix the issue with the custom component, I have also updated the file structure to follow the new specification.

let me know if it works on your environments as well

**Comment by muchasuerte** [comment]
I have also changed the way to report the operation mode and now it export also the season mode and the temperature mode
![image](https://user-images.githubusercontent.com/1520216/57180730-de43b700-6e8b-11e9-9281-32f1468b2fed.png)

**Comment by faxbio** [comment]
Great job, I ll test it soon (as soos as my daughter will let me do it :-))

I was wondering if and how try to extract also the data about alarms... It
would be useful to have a sensor in ha showing if the besmart has raised an
alarm...


Fabio

Il sab 4 mag 2019, 16:43 Andrea Nicotra <notifications@github.com> ha
scritto:

**Comment by faxbio** [comment]
Everything working fine after the update. Well done!

**Comment by renzorlive** [comment]
It's working for me too, thank you! I thought the code was interacting directly with the wifibox, not with the besmart servers, it's possible to get DHW information this way?

L.E. I can select between all modes but setting the temp from HA is not working.

**Comment by muchasuerte** [comment]
I have update the BeSmart climate to HA 0.97.0 it seems to work, I have included the battery state

**Comment by faxbio** [comment]
Hi, are your besmart integration still working fine? after few update (now my HA >0,100 ) i noticed that HA is showing the correct value from thermostat but if i try to change some setting (temp, mode etc..) from the climate component nothing happens and I can see in the debug line of the log an error . While tryin to understand it, i noticed that the android Besmart app is changed...maybe its correlated? What about your side?

**Comment by boggiano** [comment]
> Hi, are your besmart integration still working fine? after few update (now my HA >0,100 ) i noticed that HA is showing the correct value from thermostat but if i try to change some setting (temp, mode etc..) from the climate component nothing happens a

Did you update the custom component ?
I am on 0.101.2 and don't have this behaviour (I had it before the last update)
I have A LOT of warnings/errors but since this is a working in progress I just sit here waiting for the developer! :)

**Comment by faxbio** [comment]
Good news...same old story, Ha needs more than one reboot to start working as expected after some update.... :-S .
It is working now for me too.

**Comment by muchasuerte** [comment]
due to some update from the besmart () side the component is getting some strange value such 

`{'error': 0, 'outTempDependency': 'DNCON', 'tempNow': 'null', 'tempOut': '', 'cityBack': None, 'countryBack': None, 'heating': '0', 'heatingEnable': '0', 'mode': '0', 'holiday_end_time': '0', 'roomMark': '<omissis>', 'thModel': '1', 'saveT': '5.0', 'comfT': '26.0', 'frostT': '5.0', 'eS': 1, 'eC': '/A', 'bat': 'N/A', 'con': 1, 'bcon': 0, 'dhw': None, 'tempUnit': 'N/A', 'advance': 0, 'booster': 'N/A', 'season': 'null', 'cmdIssued': 'N/A', 'dhwActive': 'null', 'wifiSignal': 'null', 'boilerMode': 'N/A', 'programWeek': [['N', '/', 'A'], ['D', 'N', 'C', 'O', 'N'], ['N', '/', 'A'], ['D', 'N', 'C', 'O', 'N'], ['N', '/', 'A'], ['D', 'N', 'C', 'O', 'N'], ['N', '/', 'A']]}`

or 

`{'error': 0, 'outTempDependency': '2', 'tempNow': '17.4', 'tempOut': '13', 'cityBack': '<omissis>', 'countryBack': 'IT', 'heating': '1', 'heatingEnable': 'N/A', 'mode': '0', 'holiday_end_time': '1547506800', 'roomMark': '<omissis>', 'thModel': '5', 'saveT': '18.6', 'comfT': 'N/A', 'frostT': 'N/A', 'eS': 0, 'eC': '0', 'bat': 'N/A', 'con': 1, 'bcon': 0, 'dhw': 'N/A', 'tempUnit': '0', 'advance': 'N/A', 'booster': '0', 'season': '1', 'cmdIssued': '0', 'dhwActive': 'N/A', 'wifiSignal': '84', 'boilerMode': 0, `

I have made a commit with some change to manage some error condition (mainly to handle these cases of response with string like 'null' or 'N/A').

just an information besmart is just rebranding the backend service of this by this Chinese company http://www.cloudwarm.com, look this http://www.szacs.com/doce/product-detail-95.html 

from here is possible to download the firmware http://www.besmart-home.com/fwUpgrade/ for your wifi box maybe they do some kind of customization.

unfortunately for the moment I don't see a way to deal directly with the thermostat.

**Comment by muchasuerte** [comment]
however for the moment do not use it, I don't know why my besmart application is a bit crazy nowadays

**Comment by faxbio** [comment]
Ok, mine is crazy too.... So let's wait for a stable environment on the
besmart side...

Il mar 12 nov 2019, 21:28 Andrea Nicotra <notifications@github.com> ha
scritto:

**Comment by boggiano** [comment]
I agree with you! I'm seeing strange behaviour in the app as well.
Also, I am monitoring the availability of their server (www.besmart-home.com) and there are a lot of micro situation of unavailability.

**Comment by guciopl** [comment]
Any news in this topic? I am interested in integrating my Riello heating device controlled by besmart with HA.

**Comment by faxbio** [comment]
4 me it's working. But the vokera/besmart server itself has many issue in
these days. Even the official app is experiencing many disconnection from
the server,you can see that in the vokera / besmart Facebook group.

Il mar 8 set 2020, 19:54 guciopl <notifications@github.com> ha scritto:

**Comment by guciopl** [comment]
Perfect, but I am missing some guide how to install that component.
I saw files in 'code' tab here, but there is a lot of things connected to thermostat and I am not sure which are optional and which are obligatory.
Do I need only to recreate custom_components/besmart and put my account data there or I need to mirror configuration from all yaml files there?
customize_glob.yaml - this I dont understand completely as well as things from groups.yaml

**Comment by guciopl** [comment]
Ok, I think I have handled it well, both of my besmarts are visible in lovelace and I can control them.
I however cannot make heating history log to work correctly.

There is something like this in original config:
```
binary_sensor:
  - platform: template
    sensors: # https://www.home-assistant.io/components/binary_sensor/
      heating:
        friendly_name: "Heating"
        value_template: "{{ is_state('climate.besmart_thermostat', 'on') }}"
```

I have checked developer tools for besmart_thermostat and I noticed that there is no "heating" attribute, instead there is "heating_state" and it doesn't take "on" value at all. Instead it is false ot true. So I edited it to this, but it still doesn't work:

```
binary_sensor:
  - platform: template
    sensors: # https://www.home-assistant.io/components/binary_sensor/
      heating_state:
        friendly_name: "Heating"
        value_template: "{{ is_state('climate.besmart_parter', 'true') }}"

```

**Comment by muchasuerte** [comment]
hello 

I'm using these binary sensors

```
binary_sensor:
  - platform: template
    sensors:
      heating:
        friendly_name: "Heating"
        value_template: "{{ state_attr('climate.besmart_thermostat', 'hvac_action') == 'heating' }}"
      cooling:
        friendly_name: "Cooling"
        value_template: "{{ state_attr('climate.besmart_thermostat', 'hvac_action') == 'cooling' }}"
      thermostat_status:
        friendly_name: "Thermostat status"
        value_template: "{{ state_attr('climate.besmart_thermostat', 'heating_state') == true }}"
      battery_state:
        friendly_name: "battery state"
        device_class: battery
        value_template: "{{ state_attr('climate.besmart_thermostat', 'battery_state') == '1' }}"
        icon_template: mdi:battery
```
