### ISSUE TITLE
Can't install on HA

### ISSUE THREAD

**Issue by boggiano** [muchasuerte/home-assistant#4]
I am on 0.95.4  version.
I created a dir
/home/homeassistant/.homeassistant/custom_components/Besmart
with files:
manifest.json
__init__.py
climate.py

**manifest.json** is:
```
{
  "domain": "besmart",
  "name": "Besmart",
  "documentation": "https://github.com/muchasuerte/home-assistant/tree/master/custom_components/besmart",
  "dependencies": [],
  "codeowners": ["@royduin"],
  "requirements": []
}
```

in my configuration.yaml:
```
climate:
  - platform: Besmart
    name: Caldaia
    username: myuser
    password: mypass
    room: myroom
    scan_interval: 10
```

But I get:

> Platform not found: climate.Besmart
