### ISSUE TITLE
'Thermostat' object has no attribute '_season

### ISSUE THREAD

**Issue by boggiano** [muchasuerte/home-assistant#5]
HA version 0.99.2.

I get:

> 2019-09-28 12:48:07 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
> Traceback (most recent call last):
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 266, in async_update_ha_state
>     self._async_write_ha_state()
>   File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 308, in _async_write_ha_state
>     attr.update(self.device_state_attributes or {})
>   File "/home/homeassistant/.homeassistant/custom_components/Besmart/climate.py", line 366, in device_state_attributes
>     'season_mode': self.SEASON_BESMART_TO_HA.get(self._season)
> AttributeError: 'Thermostat' object has no attribute '_season'

In my configuration.yaml I have:

```
climate:
  - platform: Besmart
    name: Caldaia
    username: myName
    password: MyPass
    room:myRoom
    scan_interval: 10
```

Thanks!
